name: CICD Workflow
on: 
  push:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
       
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v5

      # Setup Python Environmnet
      - name: Set up Python Environment
        uses: actions/setup-python@v6
        with:
          python-version: '3.12'

      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest-cov -r requirements.txt

      # Run test cases with coverage
      - name: run test with coverage
        run: |
          pytest --cov=src tests/ --cov-report=xml --cov-report=html
  docker:
    runs-on: ubuntu-latest
    needs: test
    steps:
      # Checkout the code
      - name: Checkout the code
        uses: actions/checkout@v5

      # Login to Dockerhub
      - name: Login to Dockerhub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.Docker_Hub_Username }}
          password: ${{ secrets.Docker_Hub_Token }}

      # Build and push Docker image
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{secrets.Docker_Hub_Username }}/git-gist:${{ github.run_number}}
          file: ./Dockerfile