name: CICD Workflow
on: 
  push:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
       
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v5

      # Setup Python Environmnet
      - name: Set up Python Environment
        uses: action/setup-python@v5
        with:
          python-version: '3.12'

      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest-cov -r requirements.txt

      # Run test cases with coverage
      - name: run test with coverage
        run: |
          pytest --cov=src tests/ --cov-report=xml --cov-report=html